name: insert-ordered-containers
version: 0.1.0.1
synopsis: Associative containers retating insertion order for traversals.
description: Associative containers retating insertion order for traversals.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/insert-ordered-containers
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  >=4.5      && <4.10
  - aeson                 >=0.8.0.2  && <0.12
  - base-compat           >=0.6.0    && <0.10
  - hashable              >=1.2.3.3  && <1.4
  - lens                  >=4.7      && <4.14
  - semigroupoids         >=4.3      && <5.1
  - semigroups            >=0.16.2.2 && <0.19
  - text                  >=1.2.0.6  && <1.3
  - transformers          >=0.3.0.0  && <0.6
  - unordered-containers  >=0.2.7.0  && <0.3

library:
  source-dirs: src

tests:
  ins-ord-containers-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base
      - insert-ordered-containers
      - tasty             >= 0.10.1.2 && <0.12
      - tasty-quickcheck  >= 0.8.3.2  && <0.9
      - QuickCheck        >=2.7.6     && <2.9
